name: Building

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: 'Building'

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get FASM
        run: |
          curl https://flatassembler.net/fasmw17330.zip -O fasmw.zip
          7z x fasmw.zip
        shell: powershell

      - name: Build driver
        run: |
          fasm vbox.asm

      - name: Upload driver
        uses: actions/upload-artifact@v3
        with:
          name: driver
          path: vbox.sys
